import 'package:flutter_codefest/data/models/shelter.dart';
import 'package:geolocator/geolocator.dart';

Shelter fakeShelter({
  required int id,
  String? shelterId,
  String name = '測試避難所',
  String city = '臺北市',
  String district = '中正區',
  String address = '公園路29號',
  String type = '學校',
  String flood = 'Y',
  String earthquake = 'Y',
  String landslide = 'N',
  String tsunami = 'N',
  String indoor = 'Y',
  String outdoor = 'N',
  String accessible = 'Y',
  double? lat,
  double? lng,
  String? coordinateSource,
  String? coordinateConfidence = 'exact',
}) => Shelter(
  id: id,
  importDate: DateTime.utc(2025, 11, 28),
  shelterId: shelterId ?? 'SA100-${id.toString().padLeft(4, '0')}',
  name: name,
  city: city,
  postalCode: '100',
  district: district,
  village: '林興里',
  address: address,
  type: type,
  flood: flood,
  earthquake: earthquake,
  landslide: landslide,
  tsunami: tsunami,
  reliefStation: 'Y',
  accessible: accessible,
  indoor: indoor,
  outdoor: outdoor,
  serviceVillages: const ['板溪里', '網溪里'],
  capacity: 100,
  area: '200',
  contactName: '王小明',
  contactPhone: '02-00000000',
  managerName: '陳大文',
  managerPhone: '02-11111111',
  remarks: '',
  latitude: lat,
  longitude: lng,
  coordinateSource: coordinateSource,
  coordinateConfidence: coordinateConfidence,
);

Position fakePosition({required double lat, required double lng}) => Position(
  latitude: lat,
  longitude: lng,
  timestamp: DateTime.utc(2025, 11, 28),
  accuracy: 5,
  altitude: 0,
  altitudeAccuracy: 0,
  heading: 0,
  headingAccuracy: 0,
  speed: 0,
  speedAccuracy: 0,
);
