import 'package:server/domain/entities/shelter.dart';

/// Builds a [Shelter] with realistic defaults, so each test only states the
/// fields it actually cares about.
Shelter shelter({
  required int id,
  String? shelterCode,
  String name = '測試避難所',
  String city = '臺北市',
  String township = '中正區',
  String village = '林興里',
  String address = '公園路29號',
  String type = '學校',
  String? flood = 'Y',
  String? quake = '備用',
  String? landslide = 'N',
  String? tsunami = 'N',
  String? nuclear = 'N',
  String? relief = 'Y',
  String? accessible = 'Y',
  String? indoor = 'Y',
  String? outdoor = 'N',
  String? serviceVillages,
  int capacity = 100,
  double? area = 200,
  String? notes,
  double? x,
  double? y,
  String? coordinateSource,
  String? coordinateConfidence,
}) => Shelter(
  id: id,
  importDate: DateTime.utc(2025, 11, 28),
  shelterCode: shelterCode ?? 'SA100-${id.toString().padLeft(4, '0')}',
  name: name,
  city: city,
  zipcode: '100',
  township: township,
  village: village,
  address: address,
  type: type,
  flood: flood,
  quake: quake,
  landslide: landslide,
  tsunami: tsunami,
  nuclear: nuclear,
  relief: relief,
  accessible: accessible,
  indoor: indoor,
  outdoor: outdoor,
  serviceVillages: serviceVillages,
  capacity: capacity,
  area: area,
  contactName: '王小明',
  contactPhone: '02-00000000',
  managerName: '陳大文',
  managerPhone: '02-11111111',
  notes: notes,
  x: x,
  y: y,
  coordinateSource: coordinateSource,
  coordinateConfidence: coordinateConfidence,
);
